version: '3'
services:
  bd:
    image: postgres:latest
    environment:
      - POSTGRES_USER=tutorial_docker_owner
      - POSTGRES_PASSWORD=tutorial_docker_owner
      - POSTGRES_DB=postgres
  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=roger.n.gouveia@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 81:80
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 80:15672
  consumer:
    image: rabbithole/tutorial_docker_consumer
    depends_on:
      - bd
      - rabbitmq
    deploy:
      replicas: 4
    restart: on-failure
    environment:
      - TUTORIAL_DB_HOST=bd
      - TUTORIAL_DB_NAME=postgres
      - TUTORIAL_DB_USER=tutorial_docker_owner
      - TUTORIAL_DB_PW=tutorial_docker_owner
      - TUTORIAL_DB_PORT=5432
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PW=guest
  producer: 
    image: rabbithole/tutorial_docker_producer
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PW=guest